<script type="text/javascript">
    //<![CDATA[
    function resetData() {
        var r = confirm("Are you sure you want to reset data?");
        if (r == true) {
            new Ajax.Request('<?php echo $this->getResetAjaxUrl() ?>', {
                method:     'get',
                onCreate: function () {

                },
                onSuccess: function (response) {
                    console.log(response.responseText);
                    if (response.responseJSON) {
                        alert(response.responseJSON);
                    } else {
                        alert(response.responseText);
                    }
                },
                onFailure: function () {
                    resultBox.text('Request failed.');
                }
            });
        }
    }
    //]]>
</script>
 
<?php echo $this->getResetButtonHtml() ?>
