
<?php
$_prodSku = $this->getProdId();
$_prodPrice = $this->getProdPrice();
$_conversionId = $this->getConversionId();
?>

<!-- Google Code for Remarketing Tag -->
<!--------------------------------------------------
Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. See more information and instructions on how to setup the tag on: http://google.com/ads/remarketingsetup
--------------------------------------------------->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = <?php echo $_conversionId ?>;
    var google_custom_params = {
        ecomm_prodid: '<?php echo $_prodSku ?>',
        ecomm_pagetype: 'cart',
        ecomm_totalvalue: <?php echo $_prodPrice ?>,
    };
    var google_remarketing_only = true;
    /* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/<?php echo $_conversionId ?>/?value=0&amp;guid=ON&amp;script=0"/>
    </div>
</noscript>
