<?php

$_prodSku = $this->getProdId();
$_prodPrice = $this->getProdPrice();
$_conversionId = $this->getConversionId();
$_conversionLabel = $this->getConversionLabel();
$_currency = $this->getConversionCurrency();

?>

<!-- Google Code for Remarketing Tag -->
<!--------------------------------------------------
Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. See more information and instructions on how to setup the tag on: http://google.com/ads/remarketingsetup
--------------------------------------------------->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = <?php echo $_conversionId ?>;
    var google_custom_params = {
        ecomm_prodid: <?php echo $_prodSku ?>,
        ecomm_pagetype: "purchase",
        ecomm_totalvalue: <?php echo $_prodPrice ?>,
    };
    var google_remarketing_only = true;
    /* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/<?php echo $_conversionId ?>/?value=0&amp;guid=ON&amp;script=0"/>
    </div>
</noscript>

<!-- Google Code for Purchase Conversion Page -->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = <?php echo $_conversionId ?>;
    var google_conversion_language = "en_US";
    var google_conversion_format = "1";
    var google_conversion_color = "666666";
    var google_conversion_label = "<?php echo $_conversionLabel ?>";
    var google_conversion_currency = "<?php echo $_currency ?>";
    var google_remarketing_only = false;
    var google_conversion_value = <?php echo $_prodPrice ?>;
    /* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
    <img height=1 width=1 border=0 src="//www.googleadservices.com/pagead/
		conversion/<?php echo $_conversionId ?>/?value=<?php echo $_prodPrice ?>&amp;currency_code=<?php echo $_currency ?>&amp;label=<?php echo $_conversionLabel ?>&amp;guid=ON&amp;script=0">
</noscript>
