<!--"http://localhost:3000"    "http://magento.roihunter.com/" -->
<!-- TODO testing url-->
<iframe src="//magento.roihunter.com/"
        scrolling="yes"
        frameBorder="0"
        allowfullscreen
        align="center"
        style="width: 100%"
        id="RoihuntereasyIFrame">
    <p>Your browser does not support iFrames.</p>
</iframe>

<!--
<p>MainItem data: ?php echo($this->getMainItemEntry() ? $this->getMainItemEntry()->toString() : "Empty"); ?></p>
<p>AccessToken data: ?php echo($this->getMainItemEntry() ? $this->getMainItemEntry()->getAccessToken() : "No token"); ?></p>
<p>Creation status: ?php echo($this->getMainItemEntry() ? $this->getMainItemEntry()->getCreationState() : "No status"); ?></p>
<p>Store currency: ?php echo $this->getStoreCurrency()?></p>
<p>Store language: ?php echo $this->getStoreLanguage()?></p>
<p>Store url: ?php echo $this->getStoreBaseUrl()?></p>
-->

<div id="loadingMessage">Loading...</div>

<script>
    var storeUrl = "<?php echo $this->getStoreBaseUrl(); ?>";
    var storeName = "<?php echo $this->getStoreName(); ?>";
    var storeCurrency = "<?php echo $this->getStoreCurrency(); ?>";
    var storeLanguage = "<?php echo $this->getStoreLanguage(); ?>";
    var storeCountry = "<?php echo $this->getStoreCountry(); ?>";

    var customerId = "<?php echo($this->getMainItemEntry() ? $this->getMainItemEntry()->getCustomerId() : null); ?>";
    var accessToken = "<?php echo($this->getMainItemEntry() ? $this->getMainItemEntry()->getAccessToken() : null); ?>";
    var clientToken = "<?php echo($this->getMainItemEntry() ? $this->getMainItemEntry()->getClientToken() : null); ?>";
    var managedMerchants = "<?php echo($this->getMainItemEntry() ? $this->getMainItemEntry()->getManagedMerchants() : null); ?>";
    var adultOriented = "<?php echo($this->getMainItemEntry() ? $this->getMainItemEntry()->getAdultOriented() : null); ?>";
    var status = "<?php echo($this->getMainItemEntry() ? $this->getMainItemEntry()->getStatus() : null); ?>";
    var errors = "<?php echo($this->getMainItemEntry() ? $this->getMainItemEntry()->getErrors() : null); ?>";
    var creationState = "<?php echo($this->getMainItemEntry() ? $this->getMainItemEntry()->getCreationState() : null); ?>";


    var iFrame = document.getElementById('RoihuntereasyIFrame');
    var loadingMessageEl = document.getElementById('loadingMessage');

    iFrame.addEventListener('load', function () {
        console.log('hiding Loader');
        loadingMessageEl.style.display = 'none';

        // pass base url to React iframe fro future API calls to this site
        iFrame.contentWindow.postMessage({
                "type": "roihunter_magento_plugin",
                "storeUrl": storeUrl,
                "storeName": storeName,
                "storeCurrency": storeCurrency,
                "storeLanguage": storeLanguage,
                "storeCountry": storeCountry,

                // Database part
                "customerId": customerId,
                "accessToken": accessToken,
                "clientToken": clientToken,
                "managedMerchants": managedMerchants,
                "adultOriented": adultOriented,
                "status": status,
                "errors": errors,
                "creationState": creationState
            }, '*'
        );
    });
</script>

<script>
    // Create IE + others compatible event handler
    var eventMethod = window.addEventListener ? "addEventListener" : "attachEvent";
    var eventer = window[eventMethod];
    var messageEvent = eventMethod == "attachEvent" ? "onmessage" : "message";

    // Listen to message from child window
    eventer(messageEvent, function (e) {
        if (e.data.type === "roihunter_magento_plugin_height") {
//            Change size of iFrame to correspond new height of content
//            console.log("new height: " + e.data.height);
            document.getElementById('RoihuntereasyIFrame').style.height = e.data.height + 'px';
        } else {
//            console.log("Unknown message event", e);
        }
    }, false);

</script>
